# Generated by Django 4.0.2 on 2022-03-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0002_auto_20220119_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
