# Generated by Django 4.0.2 on 2022-03-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0003_alter_service_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='rest_server.Tag'),
        ),
    ]
