# Generated by Django 4.0.2 on 2022-03-13 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0004_alter_service_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
