# Generated by Django 4.0.2 on 2022-03-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0005_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
