# Generated by Django 4.0.2 on 2022-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0007_remove_service_image_service_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
