# Generated by Django 4.0.2 on 2022-03-18 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0009_product_remove_service_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
