# Generated by Django 4.0.2 on 2022-03-22 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0010_product_image_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PRODUCT_OWNER', 'Product Owner'), ('SCRUM_MASTER', 'Scrum Master'), ('DEVELOPER', 'Developer'), ('TESTER', 'Tester'), ('ARCHITECT', 'Architect')], max_length=30)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rest_server.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
