# Generated by Django 4.0.2 on 2022-03-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0012_alter_team_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
