# Generated by Django 4.0.2 on 2022-03-30 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0013_alter_product_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siemensuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
