# Generated by Django 4.0.5 on 2022-06-21 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0017_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='reason',
            field=models.CharField(default='Manual', max_length=50),
            preserve_default=False,
        ),
    ]
