# Generated by Django 4.0.5 on 2022-06-21 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0018_recommendation_created_recommendation_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='recommendations',
            field=models.ManyToManyField(blank=True, to='rest_server.recommendation'),
        ),
    ]
