# Generated by Django 4.0.5 on 2022-06-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_server', '0019_remove_recommendation_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
